// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7lwsAiB3NvN0a7wPBQXeE_QTLJsu0KE',
    appId: '1:361528459292:web:b376ea46e4e74e16b51fd9',
    messagingSenderId: '361528459292',
    projectId: 'flutter-fcm-novu',
    authDomain: 'flutter-fcm-novu.firebaseapp.com',
    storageBucket: 'flutter-fcm-novu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsFcjb7gr6RkN2yKZzMZACmyftq_N4O04',
    appId: '1:361528459292:android:615a854e4a863c64b51fd9',
    messagingSenderId: '361528459292',
    projectId: 'flutter-fcm-novu',
    storageBucket: 'flutter-fcm-novu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuIb_YSlHViy3xbXP_ao8f8WR7w4XHhBY',
    appId: '1:361528459292:ios:65de56c4cdf8755eb51fd9',
    messagingSenderId: '361528459292',
    projectId: 'flutter-fcm-novu',
    storageBucket: 'flutter-fcm-novu.appspot.com',
    iosBundleId: 'com.unicodeveloper.awesomeNamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuIb_YSlHViy3xbXP_ao8f8WR7w4XHhBY',
    appId: '1:361528459292:ios:2473df460cd36a13b51fd9',
    messagingSenderId: '361528459292',
    projectId: 'flutter-fcm-novu',
    storageBucket: 'flutter-fcm-novu.appspot.com',
    iosBundleId: 'com.example.awesomeNamer.RunnerTests',
  );
}
